### ISSUE TITLE
Mid-semester check-in

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/thesis-sp18-cooper-networks#2]
@andrewdjac Please respond to the following questions in a reply to this issue by Wednesday Oct 18, 5pm. Brief answers are ok.

1. What is the ultimate goal of the thesis?
2. What portion of the thesis work have you completed so far?
3. What parts of the analysis do you plan on completing by the end of the semester?
4. What sections do you expect to include in your Fall semester write up? (Note that this is due as a gitbook and PDF output on Dec 7 at 9am, I'll take a snapshot of your repo at that time.)

**Comment by andrewdjac** [comment]
1.	The goal of the thesis is to further existing research on the analysis of restricted social networks. Specifically, it relates to the application of inferential techniques to a social network given that observed data is restricted somehow. How do different techniques compare in estimating network characteristics? Which methods are better at capturing features of the latent network than others? The goal is to approach this question by performing novel inference on an existing restricted network, and comparing the results of the analysis to previous results.

2.	So far I have read all the relevant research on the subject of restricted social networks and obtained a comprehensive knowledge of the techniques used in my instructor’s existing research. That is, I’ve derived all the necessary formulas and am in the process of replicating code used in the paper’s analysis. While this is duplicating existing work, my instructor and I found that this was a necessary step for me to fully understand all the material before moving ahead with my own analysis. This included me personally reviewing some material from my Bayesian statistics class and social networks class. With a strong grasp of the methods used in his paper, I can effectively implement them into my own research.

3.	I plan on implementing at least one model on my dataset by the end of the semester. I plan to obtain the sample dataset, choose a model, derive the necessary conditionals, construct a Gibbs sampler, and find some preliminary results from running it. 

4.	I plan to include a section on a review of the existing research on the subject, specifically an in-depth overview of the methods used in my instructor’s paper. Then I plan to have a section introducing the dataset being used for the implementation. In addition, I plan to have a section detailing the methods for analysis, including the appropriate models and conditionals. If I have any preliminary results completed I will include those results in an additional section as well.
